# Generated by Django 3.2.7 on 2022-11-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_set', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='video',
            new_name='related_video',
        ),
    ]
