# Generated by Django 3.2.7 on 2022-11-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_set', '0003_frames'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frames',
            new_name='Frame',
        ),
        migrations.RenameField(
            model_name='frame',
            old_name='frames',
            new_name='frame',
        ),
    ]
