# Generated by Django 3.2.7 on 2022-11-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_set', '0005_auto_20221129_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame',
            field=models.ImageField(null=True, upload_to='api_frames/frames/'),
        ),
    ]
