# Generated by Django 3.2.7 on 2022-11-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_set', '0006_frame_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='name',
        ),
    ]
