# Generated by Django 3.2.7 on 2022-11-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='the_car',
        ),
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='car.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/videos/'),
        ),
    ]
