# Generated by Django 3.2.7 on 2022-11-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20221121_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='video',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='car.video'),
        ),
    ]
